name: LoginPass
author: moderator_man
version: 1.0
main: net.mclegacy.lp.LoginPass
commands:
  mclink:
    description: Link your in-game account to your MCLegacy account
dependencies:
  - 'com.squareup.okhttp3:okhttp:5.0.0-alpha.11'